<!-- Copyright  -->
<div class="footer-copy">
  <table>
    <tr>
      <td class="side-border">About us</td>
      <td class="side-border">Customer Services</td>
      <td class="side-border">Site Map</td>
      <td class="side-border">Search Teams</td>
      <td class="side-border">Advanced Search</td>
      <td class="side-border">Orders & Returns</td>
      <td>Contact Us</td>
    </tr>
  </table>
</div>
<div class="footer-right">
  <span>
    <a href="#">&copy;2013 Shoes Store, All Rights Reseved.</a>
  </span>
</div>