<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?= /* @escapeNotVerified */ $_menu ?>
        <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
       <li class="level0 nav-5 category-item last level-top ui-menu-item" id="search">
          <a href="#" class="level-top ui-corner-all" id="search-btn"><span class="fa fa-search search-nav"></span></a>
       </li>
    </ul>
</nav>

<script type="text/javascript">
   require(['jquery'], function($) {
       //console.log('test1');
       $('#search-btn').click(function(){
           //console.log('test2');
           $(".second-header-container").toggle();
           $("#search-btn").toggleClass("decorate-btn");

           });
   });
   </script>