<div style="padding-top: 30px;">
	<div class="column-3">
		<span> <b>CUSTOMER SERVICE</b></span></br>
		 <a style="color: gray;" href="#">FAQ</a><br/>
		 <a style="color: gray;" href="#">ORDER STATUS</a><br/>
		 <a style="color: gray;" href="#">SHIPPING INFORMATION</a><br/>
		 <a style="color: gray;" href="#">RETURN & EXCHANGES</a><br/>
		 <a style="color: gray;" href="#">SIZE CHART</a><br/>
		 <a style="color: gray;" href="#">CONTACT US</a><br/>
	</div>
	<div class="column-3">
		<span><b>RUDSAK</b></span><br/>
		<a style="color: gray;" href="#">ABOUT US</a><br/>
		<a style="color: gray;" href="#">STORE LOCATOR</a><br/>
		<a style="color: gray;" href="#">GIFT CARD</a><br/>
		<a style="color: gray;" href="#">CAREER</a><br/>
		<a style="color: gray;" href="#">WHOLESALES</a><br/>
		<a style="color: gray;" href="#">PRESS INQUIRIRES</a><br/>
		<a style="color: gray;" href="#">CORPORATE GIFTINGS</a><br/>
	</div>
	<div class="column-3" style="text-align: left;">
		<span><b>CONNECT WITH US</b></span><br/><br/>
		<a href="#"><img src="<?php echo $this->getViewFileUrl("images/facebook.png");?> "/></a> &nbsp;&nbsp;&nbsp;&nbsp;
		<a href="#"><img src="<?php echo $this->getViewFileUrl("images/twi.png");?> " /></a>&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="#"><img src="<?php echo $this->getViewFileUrl("images/pin.png");?> " /></a>&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="#"><img src="<?php echo $this->getViewFileUrl("images/instra.png");?> " /></a>&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="#"><img src="<?php echo $this->getViewFileUrl("images/youtube.png");?> " /></a>&nbsp;&nbsp;&nbsp;&nbsp;

	</div>

</div>