<?php /** * Copyright © Magento, Inc. All rights reserved. * See COPYING.txt for license details. */ ?> <div class="footer-container"><div class="footer"><?= $block->getChildHtml() ?> <p class="bugs"><?= /* @escapeNotVerified */ __('Help Us Keep Magento Healthy') ?> - <a href="http://www.magentocommerce.com/bug-tracking" target="_blank"><strong><?= /* @escapeNotVerified */ __('Report All Bugs') ?></strong></a></p><address><?= /* @escapeNotVerified */ $block->getCopyright() ?></address></div></div><div data-bind="scope: 'koexample'"><!-- ko template: getTemplate() --><!-- /ko --></div><script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "koexample": {
                            "component": "Excellence_Assignment/js/knock",
                            "template" : "Excellence_Assignment/example"
                        }
                    }
                }
            }
        }</script>