<!-- <!DOCTYPE html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></head><body> --><ul><li after="nav-section" ><button class="search-btn" type="submit"><i class="fa fa-search"></i></button></li></ul><!-- <script type="text/javascript">
   function toggleSearchBar()
   {
       var x = document.getElementsByClassName("block-search")[0];
       var y = document.getElementsByClassName("main2-header-container")[0];
       
       if (x.style.visibility === "hidden" && y.style.display === "none") {

           x.style.visibility = "visible";
           y.style.display = "block";

       } else {
           x.style.visibility = "hidden";
           y.style.display = "none";

       }
   }</script></body></html> -->