<?php if (count($block->getStores())>1): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
<div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">
   <!--  <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Language')) ?></span></strong> -->
    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger"
             id="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>"
             data-mage-init='{"dropdown":{}}'
             data-toggle="dropdown"
             data-trigger-keypress-button="true">
            <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                <span><?=($block->getStoreName()) ?></span>
            </strong>
        </div>
    </div>
</div>
<?php endif; ?>
